name: Build and Test

on:
  push

env:
  DATABASE_URL: "postgresql://nutfes:gidaifes@db:5432/postgre?schema=public"
  NEXT_PUBLIC_APIKEY: ""
  NEXT_PUBLIC_AUTHDOMAIN: ""
  NEXT_PUBLIC_PROJECTID: ""
  NEXT_PUBLIC_STORAGEBUCKET: ""
  NEXT_PUBLIC_MESSAGINGSENDERID: ""
  NEXT_PUBLIC_APPID: ""
  OPENAI_API_KEY: ""
  NEXT_PUBLIC_APP_ENV: "production"
  NEXT_PUBLIC_MINIO_ENDPOINT: ""
  NEXT_PUBLIC_PORT: 9000
  NEXT_PUBLIC_ACCESS_KEY: ''
  NEXT_PUBLIC_SECRET_KEY: ''
  NEXT_PUBLIC_ENDPOINT: 'localhost'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: npm install
        working-directory: app
        run: npm install
      - name: Build
        working-directory: app
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: formatted by workflow
